### ISSUE TITLE
Implement Offer Prompt and Tracking with TIKI SDK

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-dx#129]
As a developer, I want to show the TIKI offer prompt to the user if the user has not seen it before and track their decisions using the TIKI SDK.

### Tasks
- [ ] Create a Cookie for Tracking if user have gone through the Offer Flow. The cookie should store the TIKI ID of the user.
- [ ] Implement logic to display the offer prompt to the user if the cookie does not exist (indicating the user has not gone through the offer flow).
- [ ] Use the callback functions onAccept/onDecline to handle the user consent

**Comment by ricardobrg** [comment]
not planned
