### ISSUE TITLE
Implement pre built UI customization with Google Tag Manager data variables

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-dx#130]
As a developer I want to customize the TIKI SDK pre built UI in GTM

### Tasks
- [ ] Create GTM variables to handle pre built UI options
- [ ] Change the code to work with fallback values
- [ ] Test pre built UI examples
